insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 112', 'toyota', 'avalon', 5, 'econ', 4661);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 134', 'lincoln', 'towncar', 5, 'econ', 1756);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 154', 'lincoln', 'towncar', 5, 'econ', 5666);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 124', 'mercedes', 's-class', 5, 'lux', 7731);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 114', 'lincoln', 'towncar', 5, 'econ', 6911);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 152', 'bmw', '7 series', 5, 'lux', 2683);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 159', 'chevy', 'suburban', 7, 'suv', 4224);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 765', 'toyota', 'avalon', 5, 'econ', 2379);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 782', 'lincoln', 'towncar', 5, 'econ', 4990);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 092', 'lincoln', 'towncar', 5, 'econ', 5994);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 763', 'mercedes', 's-class', 5, 'lux', 2768);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 876', 'lincoln', 'towncar', 5, 'econ', 2685);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 986', 'bmw', '7 series', 5, 'lux', 8217);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 872', 'chevy', 'suburban', 7, 'suv', 1149);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 005', 'cadillac', 'escalade', 7, 'suv', 7954);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 009', 'chevy', 'suburban', 7, 'suv', 7462);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 564', 'toyota', 'avalon', 5, 'econ', 1859);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 076', 'cadillac', 'escalade', 7, 'suv', 2727);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 094', 'lincoln', 'towncar', 5, 'econ', 2271);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 532', 'mercedes', 's-class', 5, 'lux', 3544);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 234', 'lincoln', 'towncar', 5, 'econ', 2038);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 256', 'bmw', '7 series', 5, 'lux', 8287);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 001', 'rolls-royce', 'phantom', 4, 'suplux', 4688);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 002', 'mercedes', 'maybach', 4, 'suplux', 3999);
insert into Vehicles (plate_no, make, model, capacity, cname, uid) values ('NY 003', 'rolls-royce', 'phantom', 4, 'suplux', 8674);